name: jet_sharing
description: Jet Sharing scooter rental app.
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_riverpod: ^2.6.0
  flutter_secure_storage: ^9.2.0
  go_router: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
